fix conditional

diff --git a/nuvlabox-engine-installer/installer b/nuvlabox-engine-installer/installer
--- a/nuvlabox-engine-installer/installer
+++ b/nuvlabox-engine-installer/installer
@@ -26,13 +26,13 @@ usage()
   echo -e ""
   echo -e "UDPATE args (all mandatory):"
   echo -e " --compose-files=<list>\t\t\tComma-separated list of compose files to deploy"
-  echo -e " --current-environment=<list>\t\t\tComma-separated list of current ENV=VALUE keypairs, in case a rollback is needed"
-  echo -e " --new-environment=<list>\t\t\tComma-separated list of new ENV=VALUE keypairs"
+  echo -e " --current-environment=<list>\t\tComma-separated list of current ENV=VALUE keypairs, in case a rollback is needed"
+  echo -e " --new-environment=<list>\t\tComma-separated list of new ENV=VALUE keypairs"
   echo -e " --on-update-failure=<string>\t\tAction be take in case the update fails ${on_update_failure_options}. Default: ${on_update_failure}"
   echo -e " --project=<string>\t\t\tProject name used during the first installation"
   echo -e " --quiet\t\t\t\tOnly print final status message"
   echo -e " --target-version=<string>\t\tNuvlaBox Engine version to be installed. Must match a release from ${github_releases}"
-  echo -e " --working-dir=<string>\t\tDirectory, on the host, from where the NuvlaBox Engine was installed the first time, and where the corresponding config files can be found"
+  echo -e " --working-dir=<string>\t\t\tDirectory, on the host, from where the NuvlaBox Engine was installed the first time, and where the corresponding config files can be found"
   echo -e ""
   echo -e "UNINSTALL args:"
   echo -e " (not implemented yet)"
@@ -100,13 +100,15 @@ case ${command} in
           export quiet=1
           ;;
         --on-update-failure)
-          if [[ "${on_update_failure_options}" == *"${VALUE}"* ]]
-          then
-            export on_update_failure=${VALUE}
-          else
-            echo -e "${command} ERROR: unsupported value ${VALUE} for ${PARAM}. Must be one of ${on_update_failure_options}"
-            exit 1
-          fi
+          case $VALUE in
+            retry|ignore|rollback)
+              export on_update_failure=${VALUE}
+              ;;
+            *)
+              echo -e "${command} ERROR: unsupported value for ${PARAM}. Must be one of ${on_update_failure_options}. Got: ${VALUE}"
+              exit 1
+              ;;
+          esac
           ;;
         --new-environment)
           export environment=${VALUE}
