infer environment when not passed

diff --git a/nuvlabox-engine-installer/installer b/nuvlabox-engine-installer/installer
--- a/nuvlabox-engine-installer/installer
+++ b/nuvlabox-engine-installer/installer
@@ -27,10 +27,10 @@ usage()
   echo -e "INSTALL args:"
   echo -e " (not implemented yet)"
   echo -e ""
-  echo -e "UDPATE args (all mandatory):"
+  echo -e "UDPATE args:"
   echo -e " --compose-files=<list>\t\t\tComma-separated list of compose files to deploy"
-  echo -e " --current-environment=<list>\t\tComma-separated list of current ENV=VALUE keypairs, in case a rollback is needed"
-  echo -e " --new-environment=<list>\t\tComma-separated list of new ENV=VALUE keypairs"
+  echo -e " --current-environment=<list>\t\t(optional) Comma-separated list of current ENV=VALUE keypairs, in case a rollback is needed"
+  echo -e " --new-environment=<list>\t\t(optional) Comma-separated list of new ENV=VALUE keypairs"
   echo -e " --on-update-failure=<string>\t\tAction be take in case the update fails ${on_update_failure_options}. Default: ${on_update_failure}"
   echo -e " --project=<string>\t\t\tProject name used during the first installation"
   echo -e " --quiet\t\t\t\tOnly print final status message"
@@ -54,14 +54,30 @@ banner_intro()
   nuvlabox-engine-printer "" ${1}
 }
 
-check_mandatory_args_update()
+check_args_update()
 {
   if [[ -z $compose_files ]] || [[ -z $target_version ]] || [[ -z $quiet ]] || [[ -z $on_update_failure ]] || \
-      [[ -z $environment ]] || [[ -z $old_environment ]] || [[ -z $project ]] || [[ -z $working_dir ]]
+      [[ -z $project ]] || [[ -z $working_dir ]]
   then
     echo -e "update ERROR: missing mandatory args"
     usage
     exit 1
+  fi
+
+  if [[ -z $old_environment ]]
+  then
+    old_environment=$(nuvlabox-engine-current-env ${project} 2>&1)
+    if [[ $? -ne 0 ]]
+    then
+      echo -e "update ERROR: cannot infer --current-environment. Unable to continue"
+      exit 1
+    fi
+  fi
+
+  if [[ -z $environment ]]
+  then
+    # assume no changes to the new env
+    environment="${old_environment}"
   fi
 }
 
@@ -133,7 +149,7 @@ case ${command} in
       esac
       shift
     done
-    check_mandatory_args_update
+    check_args_update
     banner_intro ${quiet}
     output=$(nuvlabox-engine-update 2>&1 | tee /dev/fd/2)
 
